### ISSUE TITLE
Use it in a webapp

### ISSUE THREAD

**Issue by oyeanuj** [kdzwinel/Proofreader#13]
Hi @kdzwinel! I was looking to use this within a webapp, and was wondering if the library is geared towards that sort of a use and if there are any examples/demo along those lines? Thank you!

**Comment by kdzwinel** [comment]
Hey Anuj! Proofreader is a command line tool, sorry. It should be definitely possible, with some hacking, to get it working on the web. Note that it will be quite big though - as far as I remember, dictionaries are pretty huge. Good luck!
