### ISSUE TITLE
Not working on mac os installed with yarn

### ISSUE THREAD

**Issue by dylan-chong** [kdzwinel/Proofreader#14]
```
$ echo 'i stpid' > f.md
$ proofreader -f f.md
### Results for f.md ###

```

There are no suggestions for `f.md`

Using node 7.8.0, yarn 1.3.2

**Comment by kdzwinel** [comment]
Thanks for reporting. I did a quick debug, and it turns out to be one of the dependencies which introduced a breaking change. I fixed it by including package-lock.json file which locks versions of deps. Fix was published as v0.6.6 and should be already available on npm.
