### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by feross** [kdzwinel/Proofreader#4]
Is this published on npm? Searched and couldn't find it.

**Comment by kdzwinel** [comment]
Let me give you a backstory :) [This](https://github.com/GoogleChrome/devtools-docs/issues/200) is the whole reason I created this project. It was supposed to 'proofread' _one very specific_ group of documents. And if you'll look into the source code you'll find stuff specific for these docs (e.g. [custom dictionary](https://github.com/kdzwinel/Proofreader/blob/master/proofreader.js#L25) ). Proofreader is super small (~100LOC) and unimpressive (it just prints out results from two other projects), it wasn't meant for general public :) I'm OK though with making it a bit more general if people find it useful, but the big question is "how?":
- should I move all custom stuff (dictionaries, html tags that are processed) to a settings file? How would that work for `npm install proofreader -g` scenario?
- should I just create grunt/gulp wrappers for 'write-good' and 'nodehun' and abandon 'proofreader'?
- should I do something else?

I'm open for ideas.

**Comment by kdzwinel** [comment]
I ended up making it a bit more general and [publishing it to NPM](https://www.npmjs.com/package/proofreader). All custom settings were moved to a settings file.
