### ISSUE TITLE
Command line app

### ISSUE THREAD

**Issue by feross** [kdzwinel/Proofreader#5]
You can make this an easily-installable command line app if you add a "bin" property to `package.json`. Here's an example for `webtorrent`: https://github.com/feross/webtorrent/blob/master/package.json#L11

Then users can get it without using `git clone`, just like this:

```
npm install proofreader -g   // installs a `proofreader` command line program
proofreader /path/to/file
```

The `-g` tells npm to install the program globally and add it to the PATH.

**Comment by kdzwinel** [comment]
Done. Thanks for a detailed instruction!
